################################################################################################################
# Sample docker-compose file that will allow for connecting ES and HQ between separate containers
# Note that the container_name (elasticsearch) is used as a default connection url in the HQ settings.
################################################################################################################

version: '3'
services:
  elastichq:
    image: elastichq/elasticsearch-hq
    container_name: elastichq
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:9200
      - HQ_DEBUG=False
    ports:
      - 5000:5000
    networks:
      - esnet

  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - node.name=node_1
      - network.host=0.0.0.0
      - network.publish_host=0.0.0.0
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - bootstrap.system_call_filter=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

networks:
  esnet:
    driver: bridge